spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medicament-outlet
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: public